tap "getagentseal/codeburn"
tap "stablyai/orca"

brew "bat"
brew "codeburn"
brew "scc"
brew "git-delta"
brew "gh"
brew "jq"
brew "ripgrep"
brew "mise"
brew "starship"
brew "zoxide"
brew "zsh-autosuggestions"
brew "eza"
brew "rtk"
brew "mole"
brew "ollama"

# Applications
cask "brave-browser"
cask "google-chrome"
cask "thebrowsercompany-dia"
cask "transmission"
cask "vlc"
cask "font-fira-code-nerd-font"
# Self-updates via its own updater, so Homebrew's recorded version drifts behind
# the app on disk and a plain upgrade aborts on the existing bundle; force overwrites it.
cask "cleanshot", args: { force: true }
cask "linearmouse"
cask "ghostty"
cask "1password"
cask "notion"
cask "raycast"
cask "slack"
cask "spotify"
cask "cursor"
cask "claude-code"
cask "appcleaner"
cask "discord"
cask "figma"
cask "linear"
cask "beekeeper-studio"
cask "calibre"
cask "codexbar"
# Fix light & sound management with Mac + external monitor
cask "displaybuddy"
cask "plex-media-server"
cask "anki"
# Agent Development Environment; core "orca" is an unrelated deprecated cask, hence the fully-qualified tap path
cask "stablyai/orca/orca"
