tap "candid82/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"

brew "bat"
brew "cloc"
brew "diff-so-fancy"
brew "gh"
brew "git"
brew "n"
brew "jq"
brew "ripgrep"
brew "shellcheck"
brew "yarn", args: ["--ignore-dependencies"]
brew "zoxide"

cask "google-chrome"
cask "signal"
cask "transmission"
cask "spectacle"
cask "vlc"
cask "font-fira-code-nerd-font"
cask "cleanshot"
cask "iterm2"
cask "notion"
cask "raycast"
cask "rocket"
cask "slack"
cask "spotify"
cask "rectangle"
cask "visual-studio-code"
cask "zoom"
cask "wacom-inkspace"